name: blowfish
description: Blowfish encryption algorithm implementation in Dart with both ECB and CBC modes.
version: 1.0.0
repository: https://github.com/sirimathxd/Blowfish
homepage: https://github.com/sirimathxd/Blowfish
issue_tracker: https://github.com/sirimathxd/Blowfish/issues

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
